### ISSUE TITLE
 [ERROR] uncaughtException TypeError: "value" argument is

### ISSUE THREAD

**Issue by RajanZhan** [illuspas/Node-Media-Server#107]
我用FFmpeg 推流没问题，但是使用vlc 播放rtmp地址的视频时，刚开始正常，但是过了几秒钟就抛这个异常，并且视频画面就卡住了。请问这种是什么问题
3028 [ERROR] uncaughtException TypeError: "value" argument is
 out of bounds
    at checkInt (buffer.js:1178:11)
    at Buffer.writeUInt32BE (buffer.js:1271:5)
    at NodeRtmpSession.rtmpChunksCreate (D:\Project\htmlVideo\push\node_modules\
node-media-server\node_rtmp_session.js:353:14)
    at NodeRtmpSession.rtmpAudioHandler (D:\Project\htmlVideo\push\node_modules\
node-media-server\node_rtmp_session.js:623:27)
    at NodeRtmpSession.rtmpHandler (D:\Project\htmlVideo\push\node_modules\node-
media-server\node_rtmp_session.js:538:21)
    at NodeRtmpSession.rtmpChunkRead (D:\Project\htmlVideo\push\node_modules\nod
e-media-server\node_rtmp_session.js:453:18)
    at NodeRtmpSession.onSocketData (D:\Project\htmlVideo\push\node_modules\node
-media-server\node_rtmp_session.js:282:23)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)

**Comment by illuspas** [comment]
我本地没能重现，你是使用ffmpeg转推一个文件吗？
如果是的话，把这个文件发给我试试
上传到百度网盘给我个地址

**Comment by RajanZhan** [comment]
@illuspas   非常感谢你能看到这条issue，现在又好了，我自己也无法重现。我

**Comment by lanbin45** [comment]
@illuspas 您好，我在Android使用librtmp推流，将视频流保存成MP4文件时，有时候能保存，有时候不行。返回去查看日志的时候，也发现了这个错误。
我贴出部分日志内容吧，如果需要完整日志文件，欢迎联系我。

```
9/21/2018 16:33:18 23421 [INFO] [rtmp publish] Handle video. id=P0VKQ6JV streamPath=/live/6AAA120.77.202.164_1537518795.739 frame_type=1 codec_id=7 codec_name=H264 320x240
9/21/2018 16:33:18 23421 [ERROR] uncaughtException TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1041:11)
    at Buffer.writeUInt32BE (buffer.js:1134:5)
    at NodeRtmpSession.rtmpChunksCreate (/home/lanbing/Node-Media-Server/node_rtmp_session.js:353:14)
    at NodeRtmpSession.rtmpVideoHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:694:27)
    at NodeRtmpSession.rtmpHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:540:21)
    at NodeRtmpSession.rtmpChunkRead (/home/lanbing/Node-Media-Server/node_rtmp_session.js:453:18)
    at NodeRtmpSession.onSocketData (/home/lanbing/Node-Media-Server/node_rtmp_session.js:282:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
[NodeEvent on prePlay] id=PKO18I5F StreamPath=/live/6AAA120.77.202.164_1537518795.739 args={}
[NodeEvent on postPlay] id=PKO18I5F StreamPath=/live/6AAA120.77.202.164_1537518795.739 args={}
9/21/2018 16:33:18 23421 [INFO] [rtmp play] Join stream. id=PKO18I5F streamPath=/live/6AAA120.77.202.164_1537518795.739  streamId=1 
[NodeEvent on prePlay] id=DAKR8KNJ StreamPath=/live/6AAA120.77.202.164_1537518795.739 args={}
[NodeEvent on postPlay] id=DAKR8KNJ StreamPath=/live/6AAA120.77.202.164_1537518795.739 args={}
9/21/2018 16:33:18 23421 [INFO] [rtmp play] Join stream. id=DAKR8KNJ streamPath=/live/6AAA120.77.202.164_1537518795.739  streamId=1 
[NodeEvent on prePlay] id=YYMWHVVM StreamPath=/live/6BBB args={}
9/21/2018 16:33:18 23421 [INFO] [rtmp play] Stream not found. id=YYMWHVVM streamPath=/live/6BBB  streamId=1
9/21/2018 16:33:19 23421 [ERROR] Unknown field 172
9/21/2018 16:33:19 23421 [ERROR] uncaughtException TypeError: Cannot read property 'value' of null
    at Object.decodeAMF0Cmd (/home/lanbing/Node-Media-Server/node_core_amf.js:1008:17)
    at NodeRtmpSession.rtmpInvokeHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:778:29)
    at NodeRtmpSession.rtmpHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:543:21)
    at NodeRtmpSession.rtmpChunkRead (/home/lanbing/Node-Media-Server/node_rtmp_session.js:453:18)
    at NodeRtmpSession.onSocketData (/home/lanbing/Node-Media-Server/node_rtmp_session.js:282:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
[NodeEvent on preConnect] id=52VKGEJ9 args={"app":"live","flashVer":"WIN 28,0,0,137","swfUrl":"http://cdn.bdstatic.com/jwplayer/latest/cyberplayer.flash.swf","tcUrl":"rtmp://120.77.202.164/live","fpad":false,"capabilities":239,"audioCodecs":3575,"videoCodecs":252,"videoFunction":1,"pageUrl":"http://120.77.202.164/home.php","objectEncoding":0}
9/21/2018 16:33:19 23421 [INFO] [rtmp connect] id=52VKGEJ9 ip=::ffff:118.186.202.177 app=live args={"app":"live","flashVer":"WIN 28,0,0,137","swfUrl":"http://cdn.bdstatic.com/jwplayer/latest/cyberplayer.flash.swf","tcUrl":"rtmp://120.77.202.164/live","fpad":false,"capabilities":239,"audioCodecs":3575,"videoCodecs":252,"videoFunction":1,"pageUrl":"http://120.77.202.164/home.php","objectEncoding":0}
[NodeEvent on postConnect] id=52VKGEJ9 args={"app":"live","flashVer":"WIN 28,0,0,137","swfUrl":"http://cdn.bdstatic.com/jwplayer/latest/cyberplayer.flash.swf","tcUrl":"rtmp://120.77.202.164/live","fpad":false,"capabilities":239,"audioCodecs":3575,"videoCodecs":252,"videoFunction":1,"pageUrl":"http://120.77.202.164/home.php","objectEncoding":0}
9/21/2018 16:33:19 23421 [ERROR] uncaughtException TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1041:11)
    at Buffer.writeUInt32BE (buffer.js:1134:5)
    at NodeRtmpSession.rtmpChunksCreate (/home/lanbing/Node-Media-Server/node_rtmp_session.js:353:14)
    at NodeRtmpSession.rtmpVideoHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:694:27)
    at NodeRtmpSession.rtmpHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:540:21)
    at NodeRtmpSession.rtmpChunkRead (/home/lanbing/Node-Media-Server/node_rtmp_session.js:453:18)
    at NodeRtmpSession.onSocketData (/home/lanbing/Node-Media-Server/node_rtmp_session.js:282:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
9/21/2018 16:33:20 23421 [ERROR] uncaughtException TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1041:11)
    at Buffer.writeUInt32BE (buffer.js:1134:5)
    at NodeRtmpSession.rtmpChunksCreate (/home/lanbing/Node-Media-Server/node_rtmp_session.js:353:14)
    at NodeRtmpSession.rtmpVideoHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:694:27)
    at NodeRtmpSession.rtmpHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:540:21)
    at NodeRtmpSession.rtmpChunkRead (/home/lanbing/Node-Media-Server/node_rtmp_session.js:453:18)
    at NodeRtmpSession.onSocketData (/home/lanbing/Node-Media-Server/node_rtmp_session.js:282:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
[NodeEvent on prePlay] id=52VKGEJ9 StreamPath=/live/6AAA120.77.202.164_1537518795.739 args={}
[NodeEvent on postPlay] id=52VKGEJ9 StreamPath=/live/6AAA120.77.202.164_1537518795.739 args={}
9/21/2018 16:33:20 23421 [INFO] [rtmp play] Join stream. id=52VKGEJ9 streamPath=/live/6AAA120.77.202.164_1537518795.739  streamId=1 
9/21/2018 16:33:21 23421 [ERROR] uncaughtException TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1041:11)
    at Buffer.writeUInt32BE (buffer.js:1134:5)
    at NodeRtmpSession.rtmpChunksCreate (/home/lanbing/Node-Media-Server/node_rtmp_session.js:353:14)
    at NodeRtmpSession.rtmpVideoHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:694:27)
    at NodeRtmpSession.rtmpHandler (/home/lanbing/Node-Media-Server/node_rtmp_session.js:540:21)
    at NodeRtmpSession.rtmpChunkRead (/home/lanbing/Node-Media-Server/node_rtmp_session.js:453:18)
    at NodeRtmpSession.onSocketData (/home/lanbing/Node-Media-Server/node_rtmp_session.js:282:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by lanbin45** [comment]
> 我本地没能重现，你是使用ffmpeg转推一个文件吗？
> 如果是的话，把这个文件发给我试试
> 上传到百度网盘给我个地址

您好，使用librtmp在android端推流，报uncaughtException TypeError: "value" argument is out of bounds错误之后不断重启，如果需要完整日志，可以提供给你
