### ISSUE TITLE
最新1.5.0版本安装依赖后运行提示TypeError: NodeMediaServer is not a constructor

### ISSUE THREAD

**Issue by gougou168** [illuspas/Node-Media-Server#184]
最新版本安装依赖后运行提示TypeError: NodeMediaServer is not a constructor

npm  cnpm  yarn都尝试过，还是存在下面错误。切换为1.4.14版本安装模块后运行正常

```
var nms = new NodeMediaServer(config)
          ^

TypeError: NodeMediaServer is not a constructor
    at Object.<anonymous> (D:\NodejsMediaServerKoa\mediaServerApp.js:34:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by illuspas** [comment]
本人更新不兼容版本后忘记提升MAJOR了

如下修改
```
const NodeMediaServer = require('node-media-server');
```

**Comment by gougou168** [comment]
谢谢 完美解决

**Comment by 1354180465** [comment]
9040 [ERROR] Unknown command { cmd: 'FCSubscribe' }  cmd运行的时候报错，什么原因？

**Comment by cxhcmc** [comment]
ts 怎么引入？
