### ISSUE TITLE
this.gFun.next();  Error: Error: Unknown field

### ISSUE THREAD

**Issue by wuli07101** [illuspas/Node-Media-Server#2]
Node Media Server bound on port: 1935
client connect id: vbjiosoqclpn
rtmp handshake [start]
rtmp handshake [ok]
rtmp connect app: live
rtmp publish stream: stream
Unknown field 17
/data1/nodejs/Node-Media-Server/nm_bufferpool.js:21
            this.gFun.next();
                      ^

Error: Error: Unknown field
    at amfXDecodeOne (/data1/nodejs/Node-Media-Server/nm_rtmp_amf.js:887:15)
    at amf0DecodeOne (/data1/nodejs/Node-Media-Server/nm_rtmp_amf.js:898:12)
    at /data1/nodejs/Node-Media-Server/nm_rtmp_amf.js:1047:25
    at Array.forEach (native)
    at Object.decodeAMF0Cmd (/data1/nodejs/Node-Media-Server/nm_rtmp_amf.js:1045:34)
    at NMRtmpConn.NMRtmpConn.handleRtmpMessage (/data1/nodejs/Node-Media-Server/nm_rtmp_conn.js:329:31)
    at parseRtmpMessage (/data1/nodejs/Node-Media-Server/nm_rtmp_conn.js:233:18)
    at next (native)
    at BufferPool.push (/data1/nodejs/Node-Media-Server/nm_bufferpool.js:21:23)
    at Socket.<anonymous> (/data1/nodejs/Node-Media-Server/nm_server.js:19:27)

**Comment by illuspas** [comment]
fixed
