### ISSUE TITLE
when run node app.js,  I meet the following errors

### ISSUE THREAD

**Issue by andrew810810** [illuspas/Node-Media-Server#214]
use the steps: npm version (recommended)

I meet the following errors:
node-media-server/app.js:32
let nms = new NodeMediaServer(config)
    ^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by andrew810810** [comment]
The environment is centos 6.5. The node and npm version is as follows:
node -v
v0.12.10

npm -v
2.14.9

**Comment by woniuxingdong** [comment]
@andrew810810  

 _**let**_ keyword is part of ES6 standard, which is no supported by your node.

Check this out: https://node.green/

**Comment by andrew810810** [comment]
@woniuxingdong Thank you!  I update the nodejs version, and solve this issue.

**Comment by andrew810810** [comment]
@woniuxingdong Thank you!  I update the nodejs version, and solve this issue.
