### ISSUE TITLE
RTMP Camera Android App - uncaughtException TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by iongion** [illuspas/Node-Media-Server#240]
I am using *RTMP Camera* app from Android *Play Store*, I try to stream using defaults to a local server:

This is what I get:
```
7/31/2019 17:05:21 13702 [INFO] [rtmp connect] id=7MBS4TOV ip=::ffff:10.3.10.150 app=live args={"app":"live","flashVer":"LNX 9,0,124,2","tcUrl":"rtmp://10.3.10.69:1935/live","fpad":false,"capabilities":15,"audioCodecs":4071,"videoCodecs":252,"videoFunction":1}
[NodeEvent on postConnect] id=7MBS4TOV args={"app":"live","flashVer":"LNX 9,0,124,2","tcUrl":"rtmp://10.3.10.69:1935/live","fpad":false,"capabilities":15,"audioCodecs":4071,"videoCodecs":252,"videoFunction":1}
[NodeEvent on prePlay] id=7MBS4TOV StreamPath=/live/Stream1 args={}
7/31/2019 17:05:21 13702 [ERROR] uncaughtException TypeError: Cannot read property 'length' of null
    at NodeRtmpSession.onStartPlay (/opt/nms/1.0.2/node_rtmp_session.js:1121:45)
    at NodeRtmpSession.onPlay (/opt/nms/1.0.2/node_rtmp_session.js:1077:12)
    at NodeRtmpSession.rtmpInvokeHandler (/opt/nms/1.0.2/node_rtmp_session.js:827:14)
    at NodeRtmpSession.rtmpHandler (/opt/nms/1.0.2/node_rtmp_session.js:550:21)
    at NodeRtmpSession.rtmpChunkRead (/opt/nms/1.0.2/node_rtmp_session.js:458:18)
    at NodeRtmpSession.onSocketData (/opt/nms/1.0.2/node_rtmp_session.js:283:23)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
7/31/2019 17:09:22 13702 [INFO] [rtmp publish] Close stream. id=J69BITOV streamPath=/live/Stream1 streamId=1
[NodeEvent on donePublish] id=J69BITOV StreamPath=/live/Stream1 args={}
7/31/2019 17:09:22 13702 [INFO] [rtmp disconnect] id=J69BITOV
```

I the admin app, the stream seems not to play past first frame.

**Comment by lewatt23** [comment]
@iongion please how did you fix this issue ?
