### ISSUE TITLE
node apps.js error

### ISSUE THREAD

**Issue by wj2355021** [illuspas/Node-Media-Server#316]
/usr/local/Node-Media-Server-2.1.4/node_trans_server.js:21
  async run() {
        ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Node-Media-Server-2.1.4/node_media_server.js:11:25)

**Comment by hthetiot** [comment]
you probably not using Node 10+
