### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Masahigo** [illuspas/Node-Media-Server#342]
Hi,

I was testing running the _npm version_ locally (Windows 10 Pro via WSL/Ubuntu 18.04)

**ffmpeg**

```bash
$ whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz
```

**app.js**

```javascript
const NodeMediaServer = require('node-media-server');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60
  },
  http: {
    port: 8000,
    mediaroot: './media',
    allow_origin: '*'
  },
  trans: {
    ffmpeg: '/usr/bin/ffmpeg',
    tasks: [
      {
        app: 'live',
        mp4: true,
        mp4Flags: '[movflags=faststart]',
      }
    ]
  }
};

var nms = new NodeMediaServer(config)
nms.run();
```

**error**

```bash
$ node app.js
5/13/2020 09:00:12 2446 [INFO] Node Media Server v2.1.8
5/13/2020 09:00:13 2446 [INFO] Node Media Rtmp Server started on port: 1935
5/13/2020 09:00:13 2446 [INFO] Node Media Http Server started on port: 8000
5/13/2020 09:00:13 2446 [INFO] Node Media WebSocket Server started on port: 8000
(node:2446) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at NodeTransServer.run (/c/internal/nms/node_modules/node-media-server/node_trans_server.js:38:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2446) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2446) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
5/13/2020 09:11:43 2446 [INFO] [rtmp connect] id=DRMJQ546 ip=::ffff:127.0.0.1 app=live args={"app":"live","type":"nonprivate","flashVer":"FMLE/3.0 (compatible; FMSc/1.0)","swfUrl":"rtmp://localhost/live","tcUrl":"rtmp://localhost/live"}5/13/2020 09:11:43 2446 [INFO] [rtmp publish] New stream. id=DRMJQ546 streamPath=/live/testing streamId=1
5/13/2020 09:11:44 2446 [INFO] [rtmp publish] Handle audio. id=DRMJQ546 streamPath=/live/testing sound_format=10 sound_type=2 sound_size=1 sound_rate=3 codec_name=AAC 44100 2ch
5/13/2020 09:11:44 2446 [INFO] [rtmp publish] Handle video. id=DRMJQ546 streamPath=/live/testing frame_type=1 codec_id=7 codec_name=H264 1280x720
5/13/2020 09:12:02 2446 [INFO] [rtmp publish] Close stream. id=DRMJQ546 streamPath=/live/testing streamId=1
5/13/2020 09:12:02 2446 [INFO] [rtmp disconnect] id=DRMJQ546
5/13/2020 09:14:33 2446 [INFO] [rtmp connect] id=3NG17FEZ ip=::ffff:127.0.0.1 app=live args={"app":"live","type":"nonprivate","flashVer":"FMLE/3.0 (compatible; FMSc/1.0)","swfUrl":"rtmp://localhost/live","tcUrl":"rtmp://localhost/live"}5/13/2020 09:14:33 2446 [INFO] [rtmp publish] New stream. id=3NG17FEZ streamPath=/live/testing streamId=1
5/13/2020 09:14:34 2446 [INFO] [rtmp publish] Handle audio. id=3NG17FEZ streamPath=/live/testing sound_format=10 sound_type=2 sound_size=1 sound_rate=3 codec_name=AAC 44100 2ch
5/13/2020 09:14:34 2446 [INFO] [rtmp publish] Handle video. id=3NG17FEZ streamPath=/live/testing frame_type=1 codec_id=7 codec_name=H264 1280x720
5/13/2020 09:15:53 2446 [INFO] [rtmp publish] Close stream. id=3NG17FEZ streamPath=/live/testing streamId=1
5/13/2020 09:15:53 2446 [INFO] [rtmp disconnect] id=3NG17FEZ
```

Nothing seems to be saved under `media` folder when testing this locally via OBS Studio.

Did I miss something?

**Comment by Masahigo** [comment]
Nevermind, I got it working fine via Docker container.

**Dockerfile**

```dockerfile
FROM node:10.20.1-alpine

RUN apk update && \
    apk upgrade && \
    apk add 'ffmpeg>4.0.0'

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i

COPY . .

EXPOSE 1935 8000

CMD ["node","app.js"]
```
