### ISSUE TITLE
Dynamic pull through API

### ISSUE THREAD

**Issue by JohnTrabusca** [illuspas/Node-Media-Server#370]
Anyone know how to do a dynamic pull through a request to the API ? Been trying out and unfortunately can't get it to work, the ouput returns this <!DOCTYPE html>
<html lang="en">
<body>
	<pre>ReferenceError: id is not defined<br> &nbsp; &nbsp;at NodeRelayServer.onRelayPull (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/node-media-server/node_relay_server.js:91:5)<br> &nbsp; &nbsp;at EventEmitter.emit (events.js:189:13)<br> &nbsp; &nbsp;at Object.pullStream (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/node-media-server/api/controllers/relay.js:47:20)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/var/www/vhosts/naminhaterra.com/httpdocs/streamsx/node_modules/express/lib/router/index.js:275:10)</pre>
</body>

</html>`

any help it's appreciated. Thanks in advance

**Comment by pansila** [comment]
I'm looking for the answer as well. Could you show how you do the pull request through API? Thanks a lot.
