### ISSUE TITLE
Uncaught exception cant read playStreamPath of undefined - crashes server

### ISSUE THREAD

**Issue by mattcwebster** [illuspas/Node-Media-Server#399]
This uncaught exception is handled but it leaves the application in a non-working state, basically breaks the server.  

Here's the error: 

```js
9/13/2020 00:18:02 19 [ERROR] uncaughtException TypeError: Cannot read property 'playStreamPath' of undefined
    at NodeRtmpSession.onPublish (/usr/src/app/node_modules/node-media-server/node_rtmp_session.js:1038:24)
    at NodeRtmpSession.rtmpInvokeHandler (/usr/src/app/node_modules/node-media-server/node_rtmp_session.js:824:14)
    at NodeRtmpSession.rtmpHandler (/usr/src/app/node_modules/node-media-server/node_rtmp_session.js:550:21)
    at NodeRtmpSession.rtmpChunkRead (/usr/src/app/node_modules/node-media-server/node_rtmp_session.js:458:18)
    at NodeRtmpSession.onSocketData (/usr/src/app/node_modules/node-media-server/node_rtmp_session.js:283:23)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

it's in this block of code 

```js 
      for (let idlePlayerId of context.idlePlayers) {
        let idlePlayer = context.sessions.get(idlePlayerId);
        if (idlePlayer.playStreamPath === this.publishStreamPath) {
          idlePlayer.onStartPlay();
          context.idlePlayers.delete(idlePlayerId);
        }
      }
``` 

basically we should do an undefined check on line node_rtmp_session.js:1039:24.  

Steps to reproduce, if you have any authentication in the nms.on('prePublish) event - see a user has the wrong streamkey, continous calls to this will eventually produce this error, and can be replicated like such settings in OBS.  

![Screen Shot 2020-09-23 at 10 05 02 AM](https://user-images.githubusercontent.com/43913755/94031391-68900200-fd84-11ea-89a9-4645f65456ac.png)

**Comment by mattcwebster** [comment]
How can I make a pr I believe this would fix it 

```
      for (let idlePlayerId of context.idlePlayers) {
        let idlePlayer = context.sessions.get(idlePlayerId);
        if (idlePlayer && idlePlayer.playStreamPath === this.publishStreamPath) {
          idlePlayer.onStartPlay();
          context.idlePlayers.delete(idlePlayerId);
        }
      }
```
