### ISSUE TITLE
Specify required node version in package json

### ISSUE THREAD

**Issue by iongion** [illuspas/Node-Media-Server#41]
Hi, awesome project, I just tried to run the demo code after `npm install` but I got this weird error:
```
node_modules\node-media-server\api\controllers\server.js:72
async function getInfo(req, res, next) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules\node-media-server\api\routes\server.js:3:26)
```
Then I moved from *v6.11.4* to *v8.9.4* and all worked fine.
So adding ```{ "engines" : { "node" : ">=8.9.4" } }``` would be of great help, I don't know what you have as minimal requirement, I just picked up today's LTS which is *8.9.4*

**Comment by illuspas** [comment]
Oh, I was careless. 
I'm going to improve a compatible version.
