### ISSUE TITLE
server throw Index out of range  on connect rtmp ?

### ISSUE THREAD

**Issue by mortada88** [illuspas/Node-Media-Server#65]
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1015:11)
    at Buffer.readUInt8 (buffer.js:1055:5)
    at amf0decObject (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:552:34)
    at Object.amf0decArray (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:679:15)
    at amfXDecodeOne (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:821:38)
    at amf0DecodeOne (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:830:12)
    at Object.amf0decSArray (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:753:15)
    at amfXDecodeOne (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:821:38)
    at amf0DecodeOne (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:830:12)
    at amf0decObject (/Users/mahmoudmortada/live-stream-app/node_modules/node-media-server/node_core_amf.js:558:19)

**Comment by illuspas** [comment]
Please provide a sample.
