### ISSUE TITLE
Crashes when input rtmp stream is stopped from Wirecast

### ISSUE THREAD

**Issue by aidanbarrett** [illuspas/Node-Media-Server#67]
I can stream to the server with FFMPEG and start and stop without any issues but when streaming with Wirecast node will crash when I stop streaming and I get the following error:

`commandMessage.streamName.split is not a function`

I logged commandMessage.streamName and it returns `false`.

Log output:

/Users/me/Developer/rtmp/node_modules/node-media-server/node_rtmp_session.js:505
        this.publishStreamPath = '/' + this.appname + '/' + commandMessage.streamName.split('?')[0];
                                                                                      ^
TypeError: commandMessage.streamName.split is not a function
    at NodeRtmpSession.handleAMFCommandMessage (/Users/me/Developer/rtmp/node_modules/node-media-server/node_rtmp_session.js:505:87)
    at NodeRtmpSession.handleRTMPMessage (/Users/me/Developer/rtmp/node_modules/node-media-server/node_rtmp_session.js:448:14)
    at NodeRtmpSession.handleData (/Users/me/Developer/rtmp/node_modules/node-media-server/node_rtmp_session.js:304:14)
    at handleData.next (<anonymous>)
    at BufferPool.push (/Users/me/Developer/rtmp/node_modules/node-media-server/node_core_bufferpool.js:39:17)
    at NodeRtmpSession.onSocketData (/Users/me/Developer/rtmp/node_modules/node-media-server/node_rtmp_session.js:129:13)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)

NMS Setup:

```
const NodeMediaServer = require('node-media-server');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 4096,
    gop_cache: false,
    ping: 1,
    ping_timeout: 1
  },
  http: {
    port: 8000,
    mediaroot: './media',
    allow_origin: '*'
  },
  trans: {
    ffmpeg: '/usr/local/bin/ffmpeg',
    tasks: [
      {
        app: 'live',
        ac: 'aac',
        hls: true,
        hlsFlags: '[hls_time=2:hls_list_size=3:hls_flags=delete_segments]',
        dash: true,
        dashFlags: '[f=dash:window_size=3:extra_window_size=5]'
      }
    ]
  }
};

var nms = new NodeMediaServer(config)
nms.run();
```

**Comment by illuspas** [comment]
Ok, I'll try it.
