### ISSUE TITLE
Cannot read property 'api' of undefined

### ISSUE THREAD

**Issue by oscarr-reyes** [illuspas/Node-Media-Server#97]
Right after the update `1.3.6` is now throwing undefined error like this:

```
TypeError: Cannot read property 'api' of undefined
    at new NodeHttpServer (/.../node_modules/node-media-server/node_http_server.js:60:26)
    at NodeMediaServer.run (/.../node_modules/node-media-server/node_media_server.js:30:18)
    at Object.<anonymous> (/.../bin/stream:9:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

**Comment by illuspas** [comment]
You need the ‘auth’ configuration block.
But it was also a mistake. I will fix it
